tote_view_joint_angles : [-1.8936517874347132, -1.8472698370562952, 1.888345718383789, -1.385820213948385, -1.6484110991107386, 0.48918482661247253]

ARC17_ROBOT_IP : [0.0.0.0]

ARC17_R_T_MATRIX : [0.0823996,0.217731,0.972525,0.0516145,-0.685941,-0.695529,0.213834,0.109988,0.722977,-0.684714,0.092039,0.0992214,0,0,0,1]

ARC17_NO_OF_OBJECT : [50]


ARC17_OBJECT_ID: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,41,42,43,44,45,46,47,48,49,50]





ARC17_OBJECT_NAMES : [
Toilet_Brush,
Avery_Binder,
Balloons,
Band_Aid_Tape,
Bath_Sponge,
Black_Fashion_Gloves,
Burts_Bees_Baby_Wipes,
Colgate_Toothbrush_4PK,
Composition_Book,
Crayons,
Duct_Tape,
Epsom_Salts,
Expo_Eraser,
Fiskars_Scissors,
Flashlight,
Glue_Sticks,
Hand_Weight,
Hanes_Socks,
Hinged_Ruled_Index_Cards,
Ice_Cube_Tray,
Irish_Spring_Soap,
Laugh_Out_Loud_Jokes,
Marbles,
Measuring_Spoons, 
Mesh_Cup, 
Mouse_Traps, 
Pie_Plates, 
Plastic_Wine_Glass,
Poland_Spring_Water, 
Reynolds_Wrap, 
Robots_DVD, 
Robots_Everywhere, 
Scotch_Sponges, 
Speed_Stick, 
White_Facecloth,
Table_Cloth, 
Tennis_Ball_Container, 
Ticonderoga_Pencils, 
Tissue_Box, 
Windex,
a,b,c,d,e,f,g,h,i,j
]








ARC17_OBJECT_NORMAL_IGNORE: [
no,
no,
yes,
no,
yes,
yes,
no,
no,
no,
no,
no,
no,
yes,
yes,
no,
no,
yes,
yes,
no,
no,
no,
no,
yes,
yes, 
no, 
no, 
no, 
yes,
no, 
no, 
no, 
no, 
no, 
no, 
yes,
no, 
no, 
no, 
no, 
no,
no, 
no, 
no, 
no, 
yes,
no, 
no, 
no, 
no, 
no
]








ARC17_OBJECT_WEIGHT: [
heavy,
light,
light,
light,
light,
light,
light,
light,
light,
light,
light,
heavy,
light,
light,
light,
light,
heavy,
light,
light,
light,
light,
light,
light,
light, 
light, 
light, 
light, 
heavy,
heavy, 
light, 
light, 
light, 
light, 
light, 
light,
light, 
light, 
light, 
light, 
light,
light, 
light, 
light, 
light, 
light, 
light,
light, 
light, 
light, 
light, 
light
]








ARC17_OBJECT_SIZE : [
large,
large,
small,
small,
small,
small,
medium,
medium,
large,
small,
small,
medium,
small,
small,
small,
small,
small,
medium,
small,
medium,
small,
small,
small,
small,
small,
small,
medium,
small,
small,
large,
small,
small,
small,
small,
small,
medium,
medium,
medium,
small,
medium,
small,
small,
small,
small,
small,
medium,
medium,
medium,
small,
medium
]












ARC17_OBJECT_PUSH: [
1,
0,
0,
0,
2,
1,
0,
0,
0,
0,
0,
0,
0,
1,
1,
0,
1,
0,
0,
0,
0,
0,
2,
1, 
0, 
0, 
0, 
0,
0, 
0, 
0, 
0, 
0, 
0, 
1,
0, 
0, 
0, 
0, 
0,
0, 
0, 
0, 
0, 
0,
0, 
0, 
0, 
0, 
0
]


